Repository Open-Science-Community-Saudi-Arabia/MOOCs, pull requests merged in 2023-05, with the labels that each got.

#291 Weekly auto PR from `dev` into `main` branch
  client/src/components/Footer/footer.scss
  client/src/components/Footer/index.tsx
  client/src/locales/ar/messages.json
  client/src/locales/ar/messages.ts
  client/src/locales/en/messages.json
  client/src/locales/en/messages.ts
  client/src/pages/auth/login/index.tsx
  client/src/pages/home/home.scss
  documentation/README.md
  documentation/docs/tutorials/Translation.md
  documentation/docs/tutorials/contributing/contributing.json
Labels: size/M, kind/feature

#289 [11-04-2023] Translate API response
  API/package-lock.json
  API/package.json
  API/src/controllers/course.controllers.js
  API/src/utils/cloudinary.js
  API/src/utils/config.js
  API/src/utils/crowdin.js
Labels: kind/feature, size/XL

#295 [08/05/2023] fix: translation for questions
  API/src/utils/crowdin.js
Labels: size/XS

#296 [08/05/2023] Update documentation to include localisation efforts
  API/src/controllers/downloadableresources.controllers.js
  API/src/models/course.models.js
  API/src/utils/auth_codes.js
  API/src/utils/cloudinary.js
  API/src/utils/crowdin.js
  API/src/utils/token.js
  documentation/docs/tutorials/environment_setup copy.md
  documentation/docs/tutorials/localization_and_translation/backend.md
  documentation/docs/tutorials/localization_and_translation/client.md
  documentation/docs/tutorials/localization_and_translation/localization.md
  documentation/docs/tutorials/localization_and_translation/localiztion_and_translation.json
  documentation/jsdoc.json
Labels: kind/documentation, size/XL

#299 Weekly auto PR from `backend_dev` into `dev` branch
  API/src/controllers/course.controllers.js
Labels: kind/feature, size/S
