Repository Open-Science-Community-Saudi-Arabia/MOOCs, pull requests merged in 2023-02, with the labels that each got.

#180 [27/01/2023] feat: Automated PR from sub branches
  .github/workflows/auto_pr_backend_dev_to_dev.yml
  .github/workflows/auto_pr_dev_to_main.yml
  .github/workflows/auto_pr_frontend_dev_to_dev.yml
  .github/workflows/weekly_pr_from_dev_to_main.yml
Labels: enhancement

#187 [06/02/2023] Update changelog
  CHANGELOG.md
Labels: kind/documentation, size/XS

#188 [06/02/2023] fix: title of scheduled PR from `dev` to `main` branch
  .github/workflows/auto_pr_dev_to_main.yml
Labels: size/XS, fix

#190 [08/02/23] Project documentation - Server to render docs
  documentation/README.md
  documentation/docs/tutorials/api_docs.md
  documentation/docs/tutorials/backend_specific_contribution_guide.md
  documentation/docs/tutorials/changelog.md
  documentation/docs/tutorials/code_documentation.md
  documentation/docs/tutorials/contribution_guide_workflow.md
  documentation/docs/tutorials/database_model_design.md
  documentation/docs/tutorials/environment_setup.md
  documentation/docs/tutorials/frontend_specific_contribution_guide.md
  documentation/docs/tutorials/general_contribution_guides.md
  documentation/docs/tutorials/project_folder_structure.md
  documentation/docs/tutorials/tutorial.json
  documentation/package-lock.json
  documentation/package.json
  documentation/server.js
Labels: kind/documentation

#191 [08/02/2023] fix: unable to find sourcefile - jsdoc.json
  documentation/jsdoc.json
Labels: size/XS, kind/bug, fix

#192 [08/02/2023] fix: process.env config import
  documentation/server.js
Labels: kind/documentation, size/XS

#193 [08/02/2023] switch doc server to express - documentation/server.js
  documentation/server.js
Labels: kind/documentation, size/S

#194 [08/02/2023] Project doc: add express package
  documentation/package-lock.json
  documentation/package.json
Labels: kind/documentation

#195 New Crowdin updates
  client/public/locales/ar.json
Labels: kind/documentation, size/XS

#196 [20/02/2023] fix: documentation deployment
  documentation/jsdoc.json
  documentation/package-lock.json
  documentation/package.json
  documentation/server.js
Labels: kind/documentation, size/M

#197 [20/02/2023] - Update changelog
  CHANGELOG.md
Labels: kind/documentation, size/XS

#198 [20/02/2023] rename backend_API to API
  API/CONTRIBUTING.md
  API/_book/api.md
  API/_book/intro.md
  API/_book/start.md
  API/_book/toc.md
  API/book.json
  API/jsdoc.json
  API/package-lock.json
  API/package.json
  API/src/.env
  API/src/.env.dev
  API/src/.env.test
  API/src/API doc/MOOCs.postman_collection.json
  API/src/app.js
  API/src/controllers/adminauth.controllers.js
  API/src/controllers/auth.controllers.js
  API/src/controllers/course.controllers.js
  API/src/controllers/exercise.controllers.js
  API/src/controllers/question.controllers.js
  API/src/db/connectDB.js
  API/src/middlewares/auth.js
  API/src/middlewares/error_handler.js
  API/src/middlewares/permission_handler.js
  API/src/models/category.models.js
  API/src/models/course.models.js
  API/src/models/password.models.js
  API/src/models/token.models.js
  API/src/models/user.models.js
  API/src/routes/auth.routes.js
  API/src/routes/course.routes.js
  API/src/routes/exercise.routes.js
  API/src/routes/question.routes.js
  API/src/routes/routes_handler.js
  API/src/server.js
  API/src/test/0database.test.js
  API/src/test/auth.test.js
  API/src/test/courses.test.js
  API/src/utils/async_wrapper.js
  API/src/utils/auth_codes.js
  API/src/utils/config.js
  API/src/utils/email.js
  API/src/utils/errors.js
  API/src/utils/jwt_handler.js
  API/src/utils/passport.js
  API/src/utils/token.js
  API/tooling/docs/jsdoc.json
Labels: kind/documentation

#199 [20/02/2023] rename backend_API to API
  API/CONTRIBUTING.md
  API/_book/api.md
  API/_book/intro.md
  API/_book/start.md
  API/_book/toc.md
  API/book.json
  API/jsdoc.json
  API/package-lock.json
  API/package.json
  API/src/.env
  API/src/.env.dev
  API/src/.env.test
  API/src/API doc/MOOCs.postman_collection.json
  API/src/app.js
  API/src/controllers/adminauth.controllers.js
  API/src/controllers/auth.controllers.js
  API/src/controllers/course.controllers.js
  API/src/controllers/exercise.controllers.js
  API/src/controllers/question.controllers.js
  API/src/db/connectDB.js
  API/src/middlewares/auth.js
  API/src/middlewares/error_handler.js
  API/src/middlewares/permission_handler.js
  API/src/models/category.models.js
  API/src/models/course.models.js
  API/src/models/password.models.js
  API/src/models/token.models.js
  API/src/models/user.models.js
  API/src/routes/auth.routes.js
  API/src/routes/course.routes.js
  API/src/routes/exercise.routes.js
  API/src/routes/question.routes.js
  API/src/routes/routes_handler.js
  API/src/server.js
  API/src/test/0database.test.js
  API/src/test/auth.test.js
  API/src/test/courses.test.js
  API/src/utils/async_wrapper.js
  API/src/utils/auth_codes.js
  API/src/utils/config.js
  API/src/utils/email.js
  API/src/utils/errors.js
  API/src/utils/jwt_handler.js
  API/src/utils/passport.js
  API/src/utils/token.js
  API/tooling/docs/jsdoc.json
Labels: kind/documentation, inprogress

#203 deleted backend_API folder
  backend_API/CONTRIBUTING.md
  backend_API/_book/api.md
  backend_API/_book/intro.md
  backend_API/_book/start.md
  backend_API/_book/toc.md
  backend_API/book.json
  backend_API/jsdoc.json
  backend_API/package-lock.json
  backend_API/package.json
  backend_API/src/API doc/MOOCs.postman_collection.json
  backend_API/src/app.js
  backend_API/src/controllers/adminauth.controllers.js
  backend_API/src/controllers/auth.controllers.js
  backend_API/src/controllers/course.controllers.js
  backend_API/src/controllers/exercise.controllers.js
  backend_API/src/controllers/question.controllers.js
  backend_API/src/db/connectDB.js
  backend_API/src/middlewares/auth.js
  backend_API/src/middlewares/error_handler.js
  backend_API/src/middlewares/permission_handler.js
  backend_API/src/models/category.models.js
  backend_API/src/models/course.models.js
  backend_API/src/models/password.models.js
  backend_API/src/models/token.models.js
  backend_API/src/models/user.models.js
  backend_API/src/routes/auth.routes.js
  backend_API/src/routes/course.routes.js
  backend_API/src/routes/exercise.routes.js
  backend_API/src/routes/question.routes.js
  backend_API/src/routes/routes_handler.js
  backend_API/src/server.js
  backend_API/src/test/0database.test.js
  backend_API/src/test/auth.test.js
  backend_API/src/test/courses.test.js
  backend_API/src/utils/async_wrapper.js
  backend_API/src/utils/auth_codes.js
  backend_API/src/utils/config.js
  backend_API/src/utils/email.js
  backend_API/src/utils/errors.js
  backend_API/src/utils/jwt_handler.js
  backend_API/src/utils/passport.js
  backend_API/src/utils/token.js
  backend_API/tooling/docs/jsdoc.json
Labels: kind/feature

#201 [20/02/2023] - Automate running of tests
  .env.main
  .github/workflows/automated_tests.yml
  .gitignore
  API/src/controllers/auth.controllers.js
  API/src/db/connectDB.js
  API/src/middlewares/auth.js
  API/src/models/user.models.js
  API/src/server.js
  API/src/test/0database.test.js
  API/src/test/auth.test.js
  API/src/utils/config.js
Labels: enhancement, size/XL, kind/bug

#204 [24/02/2023] Unit tests - Authentication
  API/src/.env
  API/src/.env.dev
  API/src/.env.test
  API/src/models/password.models.js
  API/src/models/user.models.js
  API/src/test/auth.test.js
Labels: kind/feature, size/XL

#206 Unit test - `/verifyemail`
  API/src/controllers/auth.controllers.js
  API/src/middlewares/auth.js
  API/src/middlewares/error_handler.js
  API/src/models/token.models.js
  API/src/routes/course.routes.js
  API/src/server.js
  API/src/test/0database.test.js
  API/src/test/auth.test.js
  API/src/utils/token.js
Labels: kind/feature, size/L

#205 Weekly auto PR from refs/heads/main into `dev` branch
  backend_API/CONTRIBUTING.md
  backend_API/src/API doc/MOOCs.postman_collection.json
  backend_API/src/controllers/adminauth.controllers.js
  backend_API/src/db/connectDB.js
  backend_API/src/middlewares/auth.js
  backend_API/src/middlewares/error_handler.js
  backend_API/src/middlewares/permission_handler.js
  backend_API/src/models/category.models.js
  backend_API/src/models/course.models.js
  backend_API/src/models/password.models.js
  backend_API/src/models/token.models.js
  backend_API/src/models/user.models.js
  backend_API/src/routes/auth.routes.js
  backend_API/src/routes/course.routes.js
  backend_API/src/routes/exercise.routes.js
  backend_API/src/routes/question.routes.js
  backend_API/src/routes/routes_handler.js
  backend_API/src/server.js
  backend_API/src/test/0database.test.js
  backend_API/src/test/auth.test.js
  backend_API/src/test/courses.test.js
  backend_API/src/utils/async_wrapper.js
  backend_API/src/utils/auth_codes.js
  backend_API/src/utils/config.js
  backend_API/src/utils/email.js
  backend_API/src/utils/errors.js
  backend_API/src/utils/jwt_handler.js
  backend_API/src/utils/passport.js
  backend_API/src/utils/token.js
Labels: size/XS, kind/feature

#207 [26/02/2023] Update changelog
  CHANGELOG.md
Labels: kind/documentation, size/XS

#208 [26/02/2023] fix: mismatch in branch name for automated PR title
  .github/workflows/auto_pr_backend_dev_to_dev.yml
  .github/workflows/auto_pr_frontend_dev_to_dev.yml
Labels: kind/documentation, size/XS

#214 New Crowdin updates
  client/src/locales/ar/messages.po
Labels: kind/documentation, size/M
