Repository Open-Science-Community-Saudi-Arabia/MOOCs, pull requests merged in 2023-01, with the labels that each got.

#150 [02/01/2023] feat - Improved documentation for backend_API
  .gitignore
  CONTRIBUTING.md
  backend_API/_book/api.md
  backend_API/_book/intro.md
  backend_API/_book/start.md
  backend_API/_book/toc.md
  backend_API/book.json
  backend_API/jsdoc.json
  backend_API/package-lock.json
  backend_API/package.json
  backend_API/src/app.js
  backend_API/src/controllers/auth.controllers.js
  backend_API/src/controllers/course.controllers.js
  backend_API/src/controllers/exercise.controllers.js
  backend_API/src/controllers/question.controllers.js
  backend_API/tooling/docs/jsdoc.json
  package-lock.json
Labels: enhancement, backend development, kind/documentation, inprogress, size/XL

#153 [05/01/2023] [WIP] feat - Signin with google and github
  CONTRIBUTING.md
  backend_API/package-lock.json
  backend_API/package.json
  backend_API/src/app.js
  backend_API/src/controllers/auth.controllers.js
  backend_API/src/models/user.models.js
  backend_API/src/routes/auth.routes.js
  backend_API/src/server.js
  backend_API/src/utils/config.js
  backend_API/src/utils/passport.js
  package-lock.json
  package.json
Labels: enhancement, backend development, kind/feature, inprogress, size/XL

#159 changelog: added signin with google and github
  CHANGELOG.md
Labels: kind/documentation, size/XS

#157 [10/1/2023]: Jsdocs pages
  Frontend/README.md
  Frontend/jsdocs/api_auth.js.html
  Frontend/jsdocs/api_index.js.html
  Frontend/jsdocs/fonts/OpenSans-Bold-webfont.eot
  Frontend/jsdocs/fonts/OpenSans-Bold-webfont.svg
  Frontend/jsdocs/fonts/OpenSans-Bold-webfont.woff
  Frontend/jsdocs/fonts/OpenSans-BoldItalic-webfont.eot
  Frontend/jsdocs/fonts/OpenSans-BoldItalic-webfont.svg
  Frontend/jsdocs/fonts/OpenSans-BoldItalic-webfont.woff
  Frontend/jsdocs/fonts/OpenSans-Italic-webfont.eot
  Frontend/jsdocs/fonts/OpenSans-Italic-webfont.svg
  Frontend/jsdocs/fonts/OpenSans-Italic-webfont.woff
  Frontend/jsdocs/fonts/OpenSans-Light-webfont.eot
  Frontend/jsdocs/fonts/OpenSans-Light-webfont.svg
  Frontend/jsdocs/fonts/OpenSans-Light-webfont.woff
  Frontend/jsdocs/fonts/OpenSans-LightItalic-webfont.eot
  Frontend/jsdocs/fonts/OpenSans-LightItalic-webfont.svg
  Frontend/jsdocs/fonts/OpenSans-LightItalic-webfont.woff
  Frontend/jsdocs/fonts/OpenSans-Regular-webfont.eot
  Frontend/jsdocs/fonts/OpenSans-Regular-webfont.svg
  Frontend/jsdocs/fonts/OpenSans-Regular-webfont.woff
  Frontend/jsdocs/index.html
  Frontend/jsdocs/index.js.html
  Frontend/jsdocs/scripts/linenumber.js
  Frontend/jsdocs/scripts/prettify/Apache-License-2.0.txt
  Frontend/jsdocs/scripts/prettify/lang-css.js
  Frontend/jsdocs/scripts/prettify/prettify.js
  Frontend/jsdocs/styles/jsdoc-default.css
  Frontend/jsdocs/styles/prettify-jsdoc.css
  Frontend/jsdocs/styles/prettify-tomorrow.css
  Frontend/src/pages/auth/login/index.jsx
  Frontend/src/pages/auth/password/forgotpassword/index.jsx
  Frontend/src/pages/auth/password/reset-password/index.jsx
  Frontend/src/pages/auth/signup/index.jsx
  Frontend/src/utils/api/auth.js
  Frontend/src/utils/api/google/index.jsx
  Frontend/src/utils/api/index.js
  Frontend/src/utils/index.js
Labels: documentation, kind/documentation

#160 [13/01/2023]: Update CHANGELOG.md
  CHANGELOG.md
Labels: kind/documentation, size/XS

#161 [01/15/2023] add: MongoURI for all Environments
  backend_API/src/server.js
  backend_API/src/utils/config.js
Labels: enhancement, backend development, size/M, kind/feature, inprogress

#164 Revert "[02/01/2023] feat - Improved documentation for backend_API"
  .gitignore
  CONTRIBUTING.md
  backend_API/_book/api.md
  backend_API/_book/intro.md
  backend_API/_book/start.md
  backend_API/_book/toc.md
  backend_API/book.json
  backend_API/jsdoc.json
  backend_API/package-lock.json
  backend_API/package.json
  backend_API/src/app.js
  backend_API/src/controllers/auth.controllers.js
  backend_API/src/controllers/course.controllers.js
  backend_API/src/controllers/exercise.controllers.js
  backend_API/src/controllers/question.controllers.js
  backend_API/tooling/docs/jsdoc.json
  package-lock.json
Labels: kind/documentation

#165 [18/01/2023] feat - Improved documentation for backend_API
  .gitignore
  backend_API/_book/api.md
  backend_API/_book/intro.md
  backend_API/_book/start.md
  backend_API/_book/toc.md
  backend_API/book.json
  backend_API/jsdoc.json
  backend_API/package-lock.json
  backend_API/package.json
  backend_API/src/app.js
  backend_API/src/controllers/auth.controllers.js
  backend_API/src/controllers/course.controllers.js
  backend_API/src/controllers/exercise.controllers.js
  backend_API/src/controllers/question.controllers.js
  backend_API/tooling/docs/jsdoc.json
Labels: backend development, kind/documentation, inprogress

#168 [21/01/2023] fix: API deployment from `backend_dev`
  backend_API/package-lock.json
  backend_API/package.json
Labels: kind/bug, fix

#169 update change log to include api deployment fix, code doc feature an …
  CHANGELOG.md
Labels: kind/documentation, size/XS

#173 [24/01/2023] Update changelog for PR#166 and PR#170
  CHANGELOG.md
Labels: kind/documentation, size/XS

#174 [24/01/2023] - add dates to logs in CHANGELOG.md
  CHANGELOG.md
Labels: kind/documentation, size/S

#175 add: workflow file for Auto merge `cicd_dev` to `backend_dev`
  .github/workflows/weekly_pr_from_dev_to_main.yml
Labels: kind/documentation, size/M

#176 add date and disable main workflow
  .github/workflows/weekly_pr_from_dev_to_main.yml
Labels: size/M, kind/feature

#177 uncomment workflow file
  .github/workflows/weekly_pr_from_dev_to_main.yml
Labels: size/M, kind/feature

#178 add: workflow_dispatch
  .github/workflows/weekly_pr_from_dev_to_main.yml
  dummy.txt
Labels: kind/feature, size/S

#181 [28/01/2023] fix: auth API
  backend_API/src/controllers/auth.controllers.js
  backend_API/src/middlewares/auth.js
  backend_API/src/middlewares/error_handler.js
  backend_API/src/middlewares/permission_handler.js
  backend_API/src/models/token.models.js
  backend_API/src/models/user.models.js
  backend_API/src/routes/auth.routes.js
  backend_API/src/utils/token.js
Labels: size/L, kind/bug

#183 [29/01/23] Weekly merge from `backend_dev` to `dev`
  .gitignore
  CHANGELOG.md
  CONTRIBUTING.md
  backend_API/_book/api.md
  backend_API/_book/intro.md
  backend_API/_book/start.md
  backend_API/_book/toc.md
  backend_API/book.json
  backend_API/jsdoc.json
  backend_API/package-lock.json
  backend_API/package.json
  backend_API/src/app.js
  backend_API/src/controllers/adminauth.controllers.js
  backend_API/src/controllers/auth.controllers.js
  backend_API/src/controllers/course.controllers.js
  backend_API/src/controllers/exercise.controllers.js
  backend_API/src/controllers/question.controllers.js
  backend_API/src/middlewares/auth.js
  backend_API/src/middlewares/error_handler.js
  backend_API/src/middlewares/permission_handler.js
  backend_API/src/models/authcode.models.js
  backend_API/src/models/password.models.js
  backend_API/src/models/token.models.js
  backend_API/src/models/user.models.js
  backend_API/src/routes/auth.routes.js
  backend_API/src/server.js
  backend_API/src/utils/auth_codes.js
  backend_API/src/utils/config.js
  backend_API/src/utils/errors.js
  backend_API/src/utils/jwt_handler.js
  backend_API/src/utils/passport.js
  backend_API/src/utils/token.js
  backend_API/tooling/docs/jsdoc.json
  package-lock.json
  package.json
Labels: kind/documentation
