Repository Open-Science-Community-Saudi-Arabia/MOOCs, pull requests merged in 2023-03, with the labels that each got.

#217 [02/03/2023] set API environments
  API/src/server.js
Labels: kind/documentation, size/XS

#215 [28/02/2023] Update course feature
  .github/workflows/auto_pr_dev_to_main.yml
  API/src/controllers/adminauth.controllers.js
  API/src/controllers/auth.controllers.js
  API/src/controllers/course.controllers.js
  API/src/models/course.models.js
  API/src/routes/auth.routes.js
  API/src/routes/course.routes.js
  API/src/utils/config.js
  dummy.txt
Labels: kind/documentation, size/L

#218 [04/03/2023] feat: Exercises / Quizzes
  .github/workflows/auto_pr_backend_dev_to_dev.yml
  .github/workflows/auto_pr_dev_to_main.yml
  .github/workflows/auto_pr_frontend_dev_to_dev.yml
  API/src/app.js
  API/src/controllers/adminauth.controllers.js
  API/src/controllers/auth.controllers.js
  API/src/controllers/course.controllers.js
  API/src/controllers/exercise.controllers.js
  API/src/controllers/question.controllers.js
  API/src/models/course.models.js
  API/src/routes/auth.routes.js
  API/src/routes/course.routes.js
  API/src/routes/exercise.routes.js
  API/src/utils/alphabets.js
  API/src/utils/config.js
  CHANGELOG.md
  backend_API/package-lock.json
  backend_API/package.json
  backend_API/src/app.js
  backend_API/src/controllers/auth.controllers.js
  backend_API/src/controllers/course.controllers.js
  backend_API/src/controllers/exercise.controllers.js
  backend_API/src/controllers/question.controllers.js
  dummy.txt
Labels: kind/feature, size/L

#219 [04/03/2023] Update exercise and question features
  API/src/controllers/course.controllers.js
  API/src/controllers/exercise.controllers.js
  API/src/controllers/question.controllers.js
  API/src/models/course.models.js
  API/src/routes/course.routes.js
  API/src/routes/exercise.routes.js
  API/src/routes/question.routes.js
Labels: kind/documentation, size/L

#220 [05/03/2023] feat: Score Exercises
  API/src/controllers/exercise.controllers.js
  API/src/controllers/question.controllers.js
  API/src/models/course.models.js
  API/src/routes/exercise.routes.js
Labels: kind/feature, size/L

#221 Weekly auto PR from `backend_dev` into `dev` branch
  API/src/app.js
  API/src/controllers/course.controllers.js
  API/src/controllers/exercise.controllers.js
  API/src/controllers/question.controllers.js
  API/src/models/course.models.js
  API/src/routes/course.routes.js
  API/src/routes/exercise.routes.js
  API/src/routes/question.routes.js
  API/src/utils/alphabets.js
Labels: kind/feature, size/XL

#222 [05/03/2023] Update courses and exercises features
  .github/workflows/auto_pr_dev_to_main.yml
  API/src/app.js
  API/src/controllers/adminauth.controllers.js
  API/src/controllers/auth.controllers.js
  API/src/controllers/course.controllers.js
  API/src/controllers/exercise.controllers.js
  API/src/controllers/question.controllers.js
  API/src/models/course.models.js
  API/src/routes/auth.routes.js
  API/src/routes/course.routes.js
  API/src/routes/exercise.routes.js
  API/src/routes/question.routes.js
  API/src/server.js
  API/src/utils/alphabets.js
  API/src/utils/config.js
  dummy.txt
Labels: kind/feature

#223 [06/03/2023] feat: enrollCourse, cancelEnrollment
  API/src/controllers/course.controllers.js
  API/src/controllers/exercise.controllers.js
  API/src/models/user.models.js
  API/src/routes/course.routes.js
Labels: kind/feature, size/L

#224 Update `dev` branch from `backend_dev`
  API/src/controllers/course.controllers.js
  API/src/controllers/exercise.controllers.js
  API/src/models/user.models.js
  API/src/routes/course.routes.js
Labels: kind/documentation, size/L

#225 New Crowdin updates
  client/src/locales/ar/messages.po
Labels: kind/documentation, size/M

#227 [08/03/2023] Update quiz options datatype
  API/src/controllers/auth.controllers.js
  API/src/controllers/question.controllers.js
  API/src/models/course.models.js
Labels: kind/documentation, size/M

#228 [09/03/2023] fix: googlesignin returning 500 error
  API/src/controllers/auth.controllers.js
Labels: size/XS, kind/bug

#229 [09/03/2023] update verifyemail to point to client app
  API/src/controllers/auth.controllers.js
  API/src/utils/config.js
Labels: kind/documentation, size/XS

#235 [10/03/2023] Update googlesignin to allow `useGoogleLogin` React component
  .github/workflows/auto_pr_dev_to_main.yml
  .github/workflows/automated_tests.yml
  API/src/controllers/auth.controllers.js
  API/src/routes/auth.routes.js
  API/src/server.js
Labels: size/M, kind/feature

#236 Merge `dev` to `backend_dev` branch
  API/src/controllers/auth.controllers.js
  API/src/routes/auth.routes.js
  API/src/utils/config.js
Labels: kind/documentation, size/XS

#237 [10/03/2023] feat: Course sections
  API/src/controllers/coursesection.controllers.js
  API/src/models/course.models.js
  API/src/routes/coursesection.routes.js
  API/src/routes/routes_handler.js
Labels: enhancement, API, kind/feature, size/L

#238 Update `dev` with changes from `backend_dev`
  API/src/controllers/coursesection.controllers.js
  API/src/models/course.models.js
  API/src/routes/coursesection.routes.js
  API/src/routes/routes_handler.js
Labels: kind/documentation, size/L

#239 [11/03/2023] Improve CourseSections
  API/src/controllers/course.controllers.js
  API/src/controllers/coursesection.controllers.js
  API/src/controllers/exercise.controllers.js
  API/src/models/course.models.js
  API/src/routes/course.routes.js
  API/src/routes/coursesection.routes.js
Labels: enhancement, API, kind/feature, size/L

#243 [12/03/2023] feat: Course support for Text materials
  API/package-lock.json
  API/package.json
  API/public/tempfiles/camiscope.jpg
  API/src/controllers/auth.controllers.js
  API/src/controllers/course.controllers.js
  API/src/controllers/coursesection.controllers.js
  API/src/controllers/exercise.controllers.js
  API/src/controllers/textmaterial.controllers.js
  API/src/models/course.models.js
  API/src/routes/routes_handler.js
  API/src/routes/textmaterial.routes.js
  API/src/utils/cloudinary.js
  API/src/utils/config.js
Labels: enhancement, API, kind/feature, size/XL

#242 Weekly auto PR from `backend_dev` into `dev` branch
  API/package-lock.json
  API/package.json
  API/public/tempfiles/camiscope.jpg
  API/src/controllers/auth.controllers.js
  API/src/controllers/course.controllers.js
  API/src/controllers/coursesection.controllers.js
  API/src/controllers/exercise.controllers.js
  API/src/controllers/textmaterial.controllers.js
  API/src/models/course.models.js
  API/src/routes/course.routes.js
  API/src/routes/coursesection.routes.js
  API/src/routes/routes_handler.js
  API/src/routes/textmaterial.routes.js
  API/src/utils/cloudinary.js
  API/src/utils/config.js
Labels: kind/feature, size/XL

#241 Weekly auto PR from `dev` into `main` branch
  API/package-lock.json
  API/package.json
  API/public/tempfiles/camiscope.jpg
  API/src/controllers/auth.controllers.js
  API/src/controllers/course.controllers.js
  API/src/controllers/coursesection.controllers.js
  API/src/controllers/exercise.controllers.js
  API/src/controllers/question.controllers.js
  API/src/controllers/textmaterial.controllers.js
  API/src/models/course.models.js
  API/src/models/user.models.js
  API/src/routes/auth.routes.js
  API/src/routes/course.routes.js
  API/src/routes/coursesection.routes.js
  API/src/routes/routes_handler.js
  API/src/routes/textmaterial.routes.js
  API/src/utils/cloudinary.js
  API/src/utils/config.js
Labels: kind/feature, size/XL

#244 [12/03/2023] feat: Course certificates
  API/package-lock.json
  API/package.json
  API/src/assets/sample_certificate.png
  API/src/controllers/certificate.controllers.js
  API/src/controllers/exercise.controllers.js
  API/src/controllers/textmaterial.controllers.js
  API/src/models/certificate.models.js
  API/src/models/course.models.js
  API/src/routes/certificate.routes.js
  API/src/routes/routes_handler.js
  API/src/routes/textmaterial.routes.js
Labels: enhancement, API, kind/feature, size/XL

#245 Update `backend_dev` with changes from `dev`
  API/package-lock.json
  API/package.json
  API/public/tempfiles/camiscope.jpg
  API/src/controllers/auth.controllers.js
  API/src/controllers/coursesection.controllers.js
  API/src/controllers/exercise.controllers.js
  API/src/controllers/textmaterial.controllers.js
  API/src/models/course.models.js
  API/src/routes/coursesection.routes.js
  API/src/routes/routes_handler.js
  API/src/routes/textmaterial.routes.js
  API/src/utils/cloudinary.js
  API/src/utils/config.js
Labels: kind/documentation, size/XL

#247 Revert "[14/03/2023] Combine course contents into one array"
  .github/workflows/automated_tests.yml
  API/src/controllers/auth.controllers.js
  API/src/controllers/course.controllers.js
  API/src/controllers/exercise.controllers.js
  API/src/models/course.models.js
  API/src/routes/course.routes.js
  API/src/utils/passport.js
Labels: size/L, kind/bug

#248 [14/03/2023] Combine course contents
  API/src/controllers/exercise.controllers.js
  API/src/models/course.models.js
Labels: size/M, kind/feature

#230 New Crowdin updates
  client/src/locales/ar/messages.json
Labels: kind/documentation, size/M

#252 Weekly auto PR from `backend_dev` into `dev` branch
  API/src/controllers/exercise.controllers.js
  API/src/models/course.models.js
  API/src/utils/passport.js
Labels: size/M, kind/feature

#249 [16/03/2023] Update code documentation for authenticaion API
  .gitignore
  API/src/controllers/auth.controllers.js
  API/src/controllers/course.controllers.js
  API/src/controllers/index.js
  API/src/utils/errors.js
  documentation/.env
  documentation/jsdoc.json
  documentation/package-lock.json
  documentation/package.json
Labels: API, kind/documentation, size/XL

#251 Weekly auto PR from `dev` into `main` branch
  .gitignore
  API/src/controllers/auth.controllers.js
  API/src/controllers/course.controllers.js
  API/src/controllers/index.js
  API/src/models/course.models.js
  API/src/utils/errors.js
  API/src/utils/passport.js
  documentation/.env
  documentation/jsdoc.json
  documentation/package-lock.json
  documentation/package.json
Labels: kind/feature, size/XL

#257 [20/03/2023] Update code documentation for API - `CourseModels TokenModels`
  API/src/models/category.models.js
  API/src/models/course.models.js
  API/src/models/password.models.js
  API/src/models/token.models.js
  API/src/models/user.models.js
  API/src/seeders/add-courses.js
Labels: kind/documentation, size/XL

#258 [22/03/2023] feat: Exercise tracking
  API/src/controllers/course.controllers.js
  API/src/controllers/exercise.controllers.js
  API/src/models/course.models.js
Labels: enhancement, API, size/M, kind/feature

#261 [25/03/2023]: update: getCourse response, and scoreExercise
  API/src/controllers/course.controllers.js
  API/src/controllers/exercise.controllers.js
  API/src/middlewares/auth.js
  API/src/models/course.models.js
  API/src/routes/course.routes.js
  API/src/routes/exercise.routes.js
Labels: kind/feature, size/L

#264 [26/03/2023] fix: `GET /courses` and duplicate signup
  API/src/controllers/auth.controllers.js
  API/src/middlewares/auth.js
  API/src/routes/course.routes.js
Labels: size/M, kind/bug

#265 [26/03/2023] add record of percentage passed and best score
  API/src/controllers/exercise.controllers.js
  API/src/models/course.models.js
Labels: enhancement, API, kind/feature, size/S

#263 Weekly auto PR from `backend_dev` into `dev` branch
  API/package-lock.json
  API/package.json
  API/src/app.js
  API/src/assets/sample_certificate.png
  API/src/controllers/auth.controllers.js
  API/src/controllers/certificate.controllers.js
  API/src/controllers/course.controllers.js
  API/src/controllers/exercise.controllers.js
  API/src/controllers/textmaterial.controllers.js
  API/src/middlewares/auth.js
  API/src/middlewares/error_handler.js
  API/src/middlewares/permission_handler.js
  API/src/models/certificate.models.js
  API/src/models/course.models.js
  API/src/routes/certificate.routes.js
  API/src/routes/course.routes.js
  API/src/routes/exercise.routes.js
  API/src/routes/routes_handler.js
  API/src/routes/textmaterial.routes.js
  API/src/seeders/add-courses.js
  API/src/seeders/config.js
  API/src/seeders/index.js
  API/src/seeders/settings.js
Labels: kind/feature

#267 [28/03/2023] feat: email templates
  API/src/controllers/auth.controllers.js
  API/src/utils/email.js
  API/src/utils/email/email.js
  API/src/utils/email/templates/email_verification_template.js
  API/src/utils/email/templates/index.js
  API/src/utils/email/templates/password_reset_template.js
Labels: enhancement, API, kind/feature, size/L

#269 New Crowdin updates
  client/src/locales/ar/messages.json
Labels: kind/documentation, size/L

#270 New Crowdin updates
  client/src/locales/ar/messages.json
Labels: kind/documentation, size/M

#271 New Crowdin updates
  client/src/locales/ar/messages.json
Labels: kind/documentation, size/XS

#273 [31/03/2023] feat: downloadable resource
  API/src/controllers/downloadableresources.controllers.js
  API/src/controllers/textmaterial.controllers.js
  API/src/middlewares/auth.js
  API/src/models/course.models.js
  API/src/routes/course.routes.js
  API/src/utils/cloudinary.js
Labels: enhancement, API, kind/feature, size/L
