Repository Open-Science-Community-Saudi-Arabia/MOOCs, pull requests merged in 2023-04, with the labels that each got.

#275 Weekly auto PR from `backend_dev` into `dev` branch
  API/src/app.js
  API/src/controllers/auth.controllers.js
  API/src/controllers/course.controllers.js
  API/src/controllers/downloadableresources.controllers.js
  API/src/controllers/exercise.controllers.js
  API/src/controllers/textmaterial.controllers.js
  API/src/middlewares/auth.js
  API/src/models/course.models.js
  API/src/models/user.models.js
  API/src/routes/course.routes.js
  API/src/utils/cloudinary.js
  API/src/utils/email.js
  API/src/utils/email/email.js
  API/src/utils/email/templates/email_verification_template.js
  API/src/utils/email/templates/index.js
  API/src/utils/email/templates/password_reset_template.js
Labels: kind/feature, size/XL

#279 [04/04/2023] fix: course progress calculation
  API/src/controllers/exercise.controllers.js
  API/src/models/course.models.js
  API/src/routes/exercise.routes.js
Labels: size/M, kind/bug

#280 [04/04/2023] Documentation: Technical guide
  API/src/controllers/question.controllers.js
  API/src/routes/certificate.routes.js
  API/src/utils/alphabets.js
  API/src/utils/auth_codes.js
  API/src/utils/cloudinary.js
  API/src/utils/email/email.js
  API/src/utils/errors.js
  API/src/utils/jwt_handler.js
  API/src/utils/passport.js
  API/src/utils/token.js
  documentation/docs/tutorials/environment_setup copy.md
  documentation/docs/tutorials/technical_guide/api_guide/api.md
  documentation/docs/tutorials/technical_guide/api_guide/api_authentication_flow.md
  documentation/docs/tutorials/technical_guide/api_guide/api_structure.md
  documentation/docs/tutorials/technical_guide/api_guide/jwt_token_management.md
  documentation/docs/tutorials/technical_guide/api_guide/rbac_handler_flow.md
  documentation/docs/tutorials/technical_guide/ci_workflow.md
  documentation/docs/tutorials/technical_guide/maintainers.md
  documentation/docs/tutorials/technical_guide/reviewing_pr.md
  documentation/docs/tutorials/technical_guide/technical_guide.json
  documentation/docs/tutorials/tutorial.json
Labels: API, kind/documentation, size/XL

#281 [06/04/2023] link downloadable resources to textmaterial and video
  API/src/assets/tempfiles/RICHIE MOLUNO ___ RESUME (4).pdf
  API/src/controllers/course.controllers.js
  API/src/controllers/downloadableresources.controllers.js
  API/src/controllers/textmaterial.controllers.js
  API/src/middlewares/auth.js
  API/src/models/course.models.js
  API/src/routes/course.routes.js
Labels: kind/feature, size/L

#282 New Crowdin updates
  client/src/locales/ar/messages.json
Labels: kind/documentation, size/S

#286 Added frontend documentation
  .github/workflows/merge_crowdin
  client/README.md
  client/package.json
  client/src/App.tsx
  client/src/LocaleContext.tsx
  client/src/components/ErrorFallBack/index.tsx
  client/src/components/Footer/index.tsx
  client/src/components/LanguageToggle/index.tsx
  client/src/components/Layout/index.tsx
  client/src/components/Navbar/index.tsx
  client/src/components/ProgressBar/index.tsx
  client/src/components/Spinner/index.tsx
  client/src/data/index.ts
  client/src/hooks/useClickOutside.tsx
  client/src/hooks/useFetch.tsx
  client/src/hooks/usemediaQuery.tsx
  client/src/i18n.ts
  client/src/images/cc.png
  client/src/images/creative-common.png
  client/src/images/github-image.png
  client/src/images/github-logo.png
  client/src/images/next-flow.png
  client/src/images/nextflow.png
  client/src/images/r-logo.png
  client/src/images/verification-email-sent.jpg
  client/src/images/web3.png
  client/src/images/zenodo.png
  client/src/locales/ar/messages.json
  client/src/locales/ar/messages.ts
  client/src/locales/en/messages.json
  client/src/locales/en/messages.ts
  client/src/pages/auth/email-verify/index.tsx
  client/src/pages/auth/email-verify/style.scss
  client/src/pages/auth/forgot-password/index.tsx
  client/src/pages/auth/login/index.tsx
  client/src/pages/auth/reset-password/index.tsx
  client/src/pages/auth/signup/index.tsx
  client/src/pages/auth/style.scss
  client/src/pages/auth/verification-link/index.tsx
  client/src/pages/board/dashboard/availablecourses/index.tsx
  client/src/pages/board/dashboard/header/index.tsx
  client/src/pages/board/dashboard/index.tsx
  client/src/pages/board/viewcourse/Certificate.tsx
  client/src/pages/board/viewcourse/Quiz.tsx
  client/src/pages/board/viewcourse/ViewPdf.tsx
  client/src/pages/board/viewcourse/index.tsx
  client/src/pages/board/viewcourse/style.scss
  client/src/pages/error/index.tsx
  client/src/pages/home/home.scss
  client/src/pages/home/index.tsx
  client/src/utils/api/auth.ts
  client/src/utils/api/courses.ts
  client/src/utils/api/index.ts
  client/src/utils/index.ts
  client/yarn.lock
  documentation/jsdoc.json
Labels: documentation, MOOCs, kind/documentation

#288 New Crowdin updates
  client/src/locales/ar/messages.json
Labels: kind/documentation, size/XS

#287 [10/04/2023] Translate api email templates to arabic
  API/package-lock.json
  API/package.json
  API/src/controllers/auth.controllers.js
  API/src/utils/email/email.js
  API/src/utils/email/templates/email_verification_template.ejs
  API/src/utils/email/templates/email_verification_template_ar.ejs
  API/src/utils/email/templates/index.js
  API/src/utils/email/templates/password_reset_template.ejs
  API/src/utils/email/templates/password_reset_template.js
  API/src/utils/email/templates/password_reset_template_ar.ejs
  API/src/utils/email/templates/tmp.html
Labels: kind/feature, size/XL

#290 [11/04/2023] :Added translation tutorial
  client/src/components/Footer/footer.scss
  client/src/components/Footer/index.tsx
  client/src/locales/ar/messages.json
  client/src/locales/ar/messages.ts
  client/src/locales/en/messages.json
  client/src/locales/en/messages.ts
  client/src/pages/auth/login/index.tsx
  client/src/pages/home/home.scss
  documentation/README.md
  documentation/docs/tutorials/Translation.md
  documentation/docs/tutorials/contributing/contributing.json
Labels: documentation, MOOCs, kind/documentation, size/M
