Repository Open-Science-Community-Saudi-Arabia/MOOCs, pull requests merged in 2024-02, with the labels that each got.

#316 Client/arabic fix
  client/src/components/Footer/footer.scss
  client/src/components/Footer/index.tsx
  client/src/components/LanguageToggle/style.scss
  client/src/components/Navbar/index.tsx
  client/src/components/Navbar/navbar.scss
  client/src/pages/auth/style.scss
  client/src/pages/home/home.scss
  client/src/styles/GlobalStyles.scss
  client/src/styles/mixins.scss
Labels: size/L, kind/bug

#321 Frontend UI merge to main
  .github/workflows/merge_crowdin
  .github/workflows/merge_crowdin.yml
  client/src/components/Footer/footer.scss
  client/src/components/Footer/index.tsx
  client/src/components/LanguageToggle/style.scss
  client/src/components/Navbar/index.tsx
  client/src/components/Navbar/navbar.scss
  client/src/pages/auth/style.scss
  client/src/pages/home/home.scss
  client/src/styles/GlobalStyles.scss
  client/src/styles/mixins.scss
Labels: enhancement, size/L

#323 Github action to automate translation compilation
  .github/workflows/merge_crowdin.yml
Labels: size/M

#312 New Crowdin updates
  client/src/locales/ar/messages.json
Labels: kind/documentation, size/M

#325 Frontend UI
  .github/workflows/merge_crowdin.yml
  client/package-lock.json
  client/src/locales/ar/messages.json
  client/src/locales/ar/messages.ts
  client/yarn.lock
Labels: kind/feature

#327 fixed styling and Arabic view
  .github/workflows/merge_crowdin.yml
  client/.gitignore
  client/src/App.tsx
  client/src/components/Footer/index.tsx
  client/src/pages/auth/login/index.tsx
  client/src/pages/auth/signup/index.tsx
  client/src/pages/auth/style.scss
Labels: size/M
