Repository Open-Science-Community-Saudi-Arabia/MOOCs, pull requests merged in 2024-01, with the labels that each got.

#307 New Crowdin updates
  client/src/locales/ar/messages.json
Labels: kind/documentation, size/XS

#156 New Crowdin updates
  ar/Frontend/src
Labels: kind/documentation, size/S, localisation

#308 New Crowdin updates
  client/src/locales/ar/messages.json
Labels: kind/documentation, size/XS

#309 New Crowdin updates
  client/src/locales/ar/messages.json
Labels: kind/documentation, size/M

#310 New Crowdin updates
  client/src/locales/ar/messages.json
Labels: kind/documentation, size/S

#311 Deploy the new translation for the front-end
  API/src/utils/token.js
  client/src/components/LanguageToggle/style.scss
  client/src/components/Navbar/index.tsx
  client/src/components/Navbar/navbar.scss
  client/src/components/ProgressBar/index.tsx
  client/src/i18n.ts
  client/src/locales/ar/messages.json
  client/src/locales/ar/messages.ts
  client/src/locales/en/messages.json
  client/src/locales/en/messages.ts
  client/src/pages/board/dashboard/availablecourses/index.tsx
  client/src/pages/board/dashboard/availablecourses/style.scss
  client/src/pages/board/dashboard/index.tsx
  client/src/pages/board/viewcourse/Quiz.tsx
  client/src/pages/board/viewcourse/index.tsx
  client/src/pages/home/home.scss
  client/src/styles/GlobalStyles.scss
  client/src/styles/font/AwalRamadhan.otf
  client/src/styles/font/AwalRamadhan.ttf
  client/src/styles/font/Kahlil.ttf
  client/src/styles/font/RamadhanAmazing.ttf
  client/src/styles/font/bismillah.ttf
  client/src/types/index.tsx
  client/src/utils/api/courses.ts
  client/src/utils/api/index.ts
Labels: kind/feature, size/XL
